# Makefile for UGL Pointer Support
#
# modification history
# --------------------
# 01b,30mar05,edc  Updated Makefile for WindML 4.0
# 01a,10oct02 rfm created


C_SOURCE =	$(wildcard *.c)

DOC_FILES=	

OBJS=		$(C_SOURCE:.c=.o)

EXTRA_INCLUDE = -I$(WINDML_BASE)/src/ugl/config

include $(WINDML_BASE)/h/ugl/make/rules.windml


