#
#
#
# Automatically generated by mdiswiz 1.7.015-vxworks-1 Build Dec 20 2006 14:09:38
# 2007-09-13
#
# ts@men.de: hand edited to include necessary modules for M78 EP!

cpu {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x0
    HW_TYPE = STRING A12
    _WIZ_MODEL = STRING D3b
}
ob_mmods {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x2
    HW_TYPE = STRING A12
    _WIZ_MODEL = STRING A12_OBMMODS
    _WIZ_BUSIF = STRING cpu,0
}
m28_1 {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x1
    HW_TYPE = STRING M27_SW
    _WIZ_MODEL = STRING M28

    # ------------------------------------------------------------------------
    #        reference to base board
    # ------------------------------------------------------------------------
    BOARD_NAME = STRING ob_mmods
    DEVICE_SLOT = U_INT32 0x1

    # ------------------------------------------------------------------------
    #        device parameters
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    #        debug levels (optional)
    #        these keys have only effect on debug drivers
    # ------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008003
    DEBUG_LEVEL_MK = U_INT32 0xc0008000
    DEBUG_LEVEL_OSS = U_INT32 0xc0008000
    DEBUG_LEVEL_DESC = U_INT32 0xc0008000
}
d203_1 {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x2
    HW_TYPE = STRING D203_SW
    _WIZ_MODEL = STRING D203
    _WIZ_BUSIF = STRING cpu,1

    # ------------------------------------------------------------------------
    #        device parameters
    # ------------------------------------------------------------------------
    # --- C-PCI parameters
    PCI_BUS_PATH = BINARY 0x1e
    PCI_BUS_SLOT = U_INT32 0x4
    PCI_DEVICE_ID = U_INT32 0xd

	#--- M-Module specific Trigger Settings (see HW manual)
    MSLOT_0 {                               # M-Module #0
        TRIGA_SRC       = U_INT32  0x00		# M-Module Source TRIGA
    	TRIGA_DST       = U_INT32  0x00		# M-Module Destination TRIGA
        TRIGB_SRC       = U_INT32  0x00		# M-Module Source TRIGB
        TRIGB_DST       = U_INT32  0x00		# M-Module Destination TRIGB
    }
    MSLOT_1 {                               # M-Module #1
        TRIGA_SRC       = U_INT32  0x00		# M-Module Source TRIGA
        TRIGA_DST       = U_INT32  0x01		# M-Module Destination TRIGA
        TRIGB_SRC       = U_INT32  0x00		# M-Module Source TRIGB
        TRIGB_DST       = U_INT32  0x02		# M-Module Destination TRIGB
    }
    MSLOT_2 {                               # M-Module #2
        TRIGA_SRC       = U_INT32  0x00		# M-Module Source TRIGA
        TRIGA_DST       = U_INT32  0x00		# M-Module Destination TRIGA
        TRIGB_SRC       = U_INT32  0x00		# M-Module Source TRIGB
        TRIGB_DST       = U_INT32  0x00		# M-Module Destination TRIGB
    }
    MSLOT_3 {                               # M-Module #3
        TRIGA_SRC       = U_INT32  0x01		# M-Module Source TRIGA
        TRIGA_DST       = U_INT32  0x00		# M-Module Destination TRIGA
        TRIGB_SRC       = U_INT32  0x02		# M-Module Source TRIGB
        TRIGB_DST       = U_INT32  0x00		# M-Module Destination TRIGB
    }    

    # ------------------------------------------------------------------------
    #        debug levels (optional)
    #        these keys have only effect on debug drivers
    # ------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008000
    DEBUG_LEVEL_BK = U_INT32 0xc0008000
    DEBUG_LEVEL_OSS = U_INT32 0xc0008000
    DEBUG_LEVEL_DESC = U_INT32 0xc0008000
}
m78_1 {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x1
    HW_TYPE = STRING M78_SW
    _WIZ_MODEL = STRING M78

    # ------------------------------------------------------------------------
    #        reference to base board
    # ------------------------------------------------------------------------
    BOARD_NAME = STRING d203_1
    DEVICE_SLOT = U_INT32 0x1

    # ------------------------------------------------------------------------
    #        device parameters
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    #        debug levels (optional)
    #        these keys have only effect on debug drivers
    # ------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008003
    DEBUG_LEVEL_MK = U_INT32 0xc0008003
    DEBUG_LEVEL_OSS = U_INT32 0xc0008000
    DEBUG_LEVEL_DESC = U_INT32 0xc0008000
}
m72_pre_1 {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x1
    HW_TYPE = STRING M72_PRE_SW
    _WIZ_MODEL = STRING M72_PRE

    # ------------------------------------------------------------------------
    #        reference to base board
    # ------------------------------------------------------------------------
    BOARD_NAME = STRING d203_1
    DEVICE_SLOT = U_INT32 0x3

    # ------------------------------------------------------------------------
    #        device parameters
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    #        debug levels (optional)
    #        these keys have only effect on debug drivers
    # ------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008003
    DEBUG_LEVEL_MK = U_INT32 0xc0008000
    DEBUG_LEVEL_OSS = U_INT32 0xc0008000
    DEBUG_LEVEL_DESC = U_INT32 0xc0008000
}
m36_1  {
	#------------------------------------------------------------------------
	#	general parameters (don't modify)
	#------------------------------------------------------------------------
    DESC_TYPE       = U_INT32       1         # descriptor type (1=device)
	HW_TYPE         = STRING        M36_SW      # hardware name of device

	#------------------------------------------------------------------------
	#	base board configuration
	#------------------------------------------------------------------------
    BOARD_NAME = STRING ob_mmods
    DEVICE_SLOT = U_INT32 0x0

	#------------------------------------------------------------------------
	#	device parameters
	#------------------------------------------------------------------------
	ID_CHECK        = U_INT32   0             # check module ID prom
}
m8_1  {
	#------------------------------------------------------------------------
	#	general parameters (don't modify)
	#------------------------------------------------------------------------
    DESC_TYPE       = U_INT32       1         # descriptor type (1=device)
    HW_TYPE         = STRING        M8_SW   # hardware name of device

	#------------------------------------------------------------------------
	#	base board configuration
	#------------------------------------------------------------------------
    BOARD_NAME      = STRING        ob_mmods  # device name of baseboard
    DEVICE_SLOT     = U_INT32       2         # used slot on baseboard (0..n)

    # ------------------------------------------------------------------------
    #        debug levels (optional)
    #        these keys have only effect on debug drivers
    # ------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008000
    DEBUG_LEVEL_MK = U_INT32 0xc0008000
    DEBUG_LEVEL_OSS = U_INT32 0xc0008000
    DEBUG_LEVEL_DESC = U_INT32 0xc0008000

	#------------------------------------------------------------------------
	#	device parameters
	#------------------------------------------------------------------------
	M8_ADDRESS		= U_INT32		8		  # device address(Knick EP)

}
mmodprg_0 {
	#------------------------------------------------------------------------
	#	general parameters (don't modify)
	#------------------------------------------------------------------------
    DESC_TYPE        = U_INT32  1           # descriptor type (1=device)
    HW_TYPE          = STRING   MMODPRG_SW  # hardware name of device

	#------------------------------------------------------------------------
	#	reference to base board
	#------------------------------------------------------------------------
    BOARD_NAME       = STRING   ob_mmods    # device name of baseboard
    DEVICE_SLOT      = U_INT32  0           # used slot on baseboard (0..n)

	#------------------------------------------------------------------------
	#	device parameters
	#------------------------------------------------------------------------
}
mmodprg_1 {
	#------------------------------------------------------------------------
	#	general parameters (don't modify)
	#------------------------------------------------------------------------
    DESC_TYPE        = U_INT32  1           # descriptor type (1=device)
    HW_TYPE          = STRING   MMODPRG_SW  # hardware name of device

	#------------------------------------------------------------------------
	#	reference to base board
	#------------------------------------------------------------------------
    BOARD_NAME       = STRING   ob_mmods    # device name of baseboard
    DEVICE_SLOT      = U_INT32  1           # used slot on baseboard (0..n)

	#------------------------------------------------------------------------
	#	device parameters
	#------------------------------------------------------------------------
}
mmodprg_2 {
	#------------------------------------------------------------------------
	#	general parameters (don't modify)
	#------------------------------------------------------------------------
    DESC_TYPE        = U_INT32  1           # descriptor type (1=device)
    HW_TYPE          = STRING   MMODPRG_SW  # hardware name of device

	#------------------------------------------------------------------------
	#	reference to base board
	#------------------------------------------------------------------------
    BOARD_NAME       = STRING   ob_mmods    # device name of baseboard
    DEVICE_SLOT      = U_INT32  2           # used slot on baseboard (0..n)

	#------------------------------------------------------------------------
	#	device parameters
	#------------------------------------------------------------------------
}
# EOF
